# Generated by Django 5.1.3 on 2024-12-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0004_orderdeliver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderDeliver',
            new_name='OrderDelivery',
        ),
    ]
