# Generated by Django 5.1.3 on 2024-12-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estore', '0005_rename_orderdeliver_orderdelivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='Estore/files/products_images'),
            preserve_default=False,
        ),
    ]
